### ISSUE TITLE
Ship Contract Qualification

### ISSUE THREAD

**Issue by codegangsta** [codegangsta/Astroneer#8]
Add a basic ship qualification feature that has some minimum qualifications to meet the contract, for example:

`Ship A: <XX Mass, XX Ballistic Weapon power`.

We can eventually pull from a pool of rankings, sorted by difficulty, and randomly pull from a subsection every time a contract is generated, allowing these to generally be "Radiant" in nature.

Depends on #7 

## Tasks

- [ ] Decide which properties to start with
- [ ] Add qualification struct with some basic properties
- [ ] Start with a static pool of structs to start with
- [ ] Prevent players from turning in a ship until qualifications are met
- [ ] Research whether we can easily get the weight of the ship

## Qualification Properties

- Mass
- Engine power
- Weapon power (per category)
- Reactor Power
- Shield Power

## Other random thoughts

- A good counter-balance would be to use weight as a potential anchor, then pick 2 attributes from a pool to challenge the player toward a certain build.

**Comment by codegangsta** [comment]
This system is mostly in now, just need to implement more objectives
